apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingappapi-depl
  labels:
    app: shoppingappapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  shoppingappapi
  template:
    metadata:
      labels:
        app:  shoppingappapi
    spec:
      containers:
        - name: shoppingappapi
          image: aldosanshoppingappacr.azurecr.io/shoppingappapi:v1
          imagePullPolicy:  IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value:  Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongodb-cfgmap
                  key: mongodb_connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingappapi-srv
spec:
  selector:
    app: shoppingappapi
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1      
kind: ConfigMap
metadata:
  name: shoppingappapi-cfgmap
data:
  shoppingappapi_url: http://shoppingappapi-srv
